import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().port().default(3001),
  DATABASE_URL: Joi.string().required(),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRES_IN: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().required(),
  AWS_REGION: Joi.string().required(),
  // AWS_ACCESS_KEY_ID: Joi.string().required(),
  // AWS_SECRET_ACCESS_KEY: Joi.string().required(),
  // AWS_S3_BUCKET: Joi.string().required(),
  FRONTEND_URL: Joi.string().uri().required(),
  MAIL_FROM: Joi.string().optional(),
  RESEND_API_KEY: Joi.string().allow('').optional(),
  // GOOGLE_CLIENT_ID: Joi.string().required(),
  // GOOGLE_CLIENT_SECRET: Joi.string().required(),
  GOOGLE_CALLBACK_URL: Joi.string().uri().optional(),
  APPLE_CLIENT_ID: Joi.string().allow('').optional(),
  APPLE_TEAM_ID: Joi.string().allow('').optional(),
  APPLE_KEY_ID: Joi.string().allow('').optional(),
  APPLE_PRIVATE_KEY: Joi.string().allow('').optional(),
  THROTTLE_TTL_MS: Joi.number().integer().min(1000).optional(),
  THROTTLE_LIMIT: Joi.number().integer().min(1).optional(),
  THROTTLE_AUTH_LIMIT: Joi.number().integer().min(1).optional(),
  THROTTLE_WRITE_LIMIT: Joi.number().integer().min(1).optional(),
  THROTTLE_PAYMENTS_LIMIT: Joi.number().integer().min(1).optional(),
  THROTTLE_MESSAGING_LIMIT: Joi.number().integer().min(1).optional(),
  THROTTLE_GEOCODING_LIMIT: Joi.number().integer().min(1).optional(),
  YANDEX_MAPS_API_KEY: Joi.string().allow('').optional(),
  REDIS_URL: Joi.string().allow('').optional(),
  TRUST_PROXY: Joi.string().valid('true', 'false').optional(),
  JSON_BODY_LIMIT: Joi.string().optional(),
  MAX_UPLOAD_BYTES: Joi.number().integer().min(1).optional(),
});
